name:                brightsidebudget2
version:             0.1.0
github:              "archambaultv/brightsidebudget2"
license:             BSD-3-Clause
author:              "Vincent Archambault-B"
maintainer:          "vincentarchambault@icloud.com"
copyright:           "2024 Vincent Archambault-B"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/archambaultv/brightsidebudget2#readme>

dependencies:
- base >= 4.7 && < 5
- text
- time
- cassava

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

# executables:
#   brightsidebudget2-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - brightsidebudget2

tests:
  brightsidebudget2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brightsidebudget2
